name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2
          extensions: mbstring, intl, sqlite, pdo_sqlite, pcntl
      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
      - run: composer install --no-interaction --prefer-dist
      - name: Prepare env
        run: |
          cp .env.example .env
          php -r "file_exists('database/database.sqlite') || touch('database/database.sqlite');"
          php artisan key:generate
          php artisan migrate --force
      - name: Code style (Pint)
        run: vendor/bin/pint -v
      - name: Static analysis (Larastan)
        run: vendor/bin/phpstan analyse --memory-limit=1G
      - name: Tests
        run: php artisan test --parallel
